version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_bot
    depends_on:
      - mongo
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MONGO_URI=mongodb://mongo:27017/telegram_stats
    volumes:
      - .:/usr/src/app
    command: python ./bot.py

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
